# questo dockerfile serve ad avviare il client che chiamerà il contro controller che espone il modello

FROM python:3.10
WORKDIR /app
COPY requirements.load.txt .
RUN pip install -r requirements.load.txt
COPY esercitazione_post.py .
CMD ["python", "esercitazione_post.py"]
